version: '3'
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - .:/config
      - ~/syslogs:/var/log
    ports:
      - 514:5514/udp
    restart: unless-stopped
